ecommerce_ecommerce_homepage:
    path:     /
    defaults: { _controller: EcommerceEcommerceBundle:Default:index }

ecommerce_ecommerce_produits:
    path:     /produits
    defaults: { _controller: EcommerceEcommerceBundle:Produits:index }
    
ecommerce_ecommerce_produit:
    path:     /produit/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Produit:index }
    
ecommerce_ecommerce_admin:
    path:     /admin
    defaults: { _controller: EcommerceEcommerceBundle:Admin:index }   
    
ecommerce_ecommerce_admin_ProduitAddForm:
    path:     /admin/ProduitAddForm
    defaults: { _controller: EcommerceEcommerceBundle:Admin:ProduitAddForm } 
    
ecommerce_ecommerce_admin_ProduitEditFormModal:
    path:     /admin/ProduitEditFormModal
    defaults: { _controller: EcommerceEcommerceBundle:Admin:ProduitEditFormModal }    

ecommerce_ecommerce_admin_ProduitdeleteForm:
    path:     /admin/ProduitdeleteForm
    defaults: { _controller: EcommerceEcommerceBundle:Admin:ProduitdeleteForm }
    
ecommerce_ecommerce_admin_CategorieAddForm:
    path: /admin/CategorieAddForm
    defaults: { _controller: EcommerceEcommerceBundle:Admin:CategorieAddForm } 