<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieRepository extends \Doctrine\ORM\EntityRepository
{
   
}
