<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * produitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProduitsEnfant($categorie){

         $qb = $this->createQueryBuilder('a');

           $qb
      ->join('a.categorie', 'c')
      ->addSelect('c')
      ->leftJoin('a.image', 'image')
      ->addSelect('image');
    ;

    $qb
        ->where($qb->expr()->eq('c.parent', $categorie))
        ->orWhere($qb->expr()->eq('c.id', $categorie));
    
        return $qb
          ->getQuery()
          ->getArrayResult()
        ;
          }
          
        public function findProduits($categorie){

         $qb = $this->createQueryBuilder('a');
    
        $qb
        ->where('a.categorie = :categorie')
        ->setParameter('categorie', $categorie)
        ->leftJoin('a.image', 'image')
        ->addSelect('image')
  ;
    
        return $qb
          ->getQuery()
          ->getArrayResult()
        ;
          }
}
